[tool.poetry]
name = "entangled"
version = "2.0.0-alpha-1"
description = "Python port of Entangled"
authors = ["Johan Hidding <j.hidding@esciencecenter.nl>"]
license = "Apache 2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"          # we need tomllib support
mawk = {path = "../mawk"} # use mawk as line parsing engine
watchdog = "^3.0.0"       # file watching
click = "^8.1.3"          # command-line
filelock = "^3.12.0"      # file lock for json db


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
mypy = "^1.3.0"
black = "^23.3.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "test"
]

[tool.mypy]
packages = ["entangled"]
enable_incomplete_feature = ["TypeVarTuple"]

[tool.poetry.scripts]
entangled = "entangled.main:main"
